# Generated by Django 5.0.14 on 2026-02-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='urgency_score',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
